ldap:
  host: 167.99.221.214
  dn: dc=ldap,dc=ivan,dc=site


vpn: 
  ip : 10.0.0.1/16
  device : wg0
  host : 192.168.2.1
  port : 6543
  private_key: /key
  vpn-subnet: 10.0.0.0/16
  vpn-subnet6:
  routing-subnets:
  - 192.168.0.0/24
  - 192.168.1.0/24
  - 10.1.0.0/16

  reserved-ips:
  - 10.0.0.1
